pipeline:
  test:
    image: node:latest
    commands:
      - npm install
      - npm run test
      - npm run build

  #Runs only when push to master
  docker:
    when:
      branch: master
      event: push
    image: plugins/docker
    secrets: [ docker_username, docker_password ] # Stored in Drone admin but not available to pull request events for security
    repo: unfrgivn/drone-client-test #Defaults to Docker Hub
    tags:
      - latest
      - "${DRONE_COMMIT:0:8}"

  deploy:
    when:
      branch: master
      event: push
    image: appleboy/drone-scp
    host: 10.10.10.217
    secrets: [ ssh_username, ssh_password ]
    port: 22
    target: /home/bash/drone-deployments/ci-test.cigsecure.com/${DRONE_COMMIT}
    source: ./

  deploy-cleanup:
    when:
      branch: master
      event: push
    image: appleboy/drone-ssh
    host: 10.10.10.217
    secrets: [ ssh_username, ssh_password ]
    port: 22
    script:
      - ln -sfn /home/bash/drone-deployments/ci-test.cigsecure.com/${DRONE_COMMIT} /home/bash/ci-test.cigsecure.com
      - rm -r `ls /home/bash/drone-deployments/ci-test.cigsecure.com/ -1 | sort -r | tail -n +3`
